{{- if .Values.applications.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: {{ .Values.applications.argocd.chart }}
    repoURL: {{ .Values.applications.argocd.repoURL }}
    targetRevision: {{ .Values.applications.argocd.version }}
    helm:
      releaseName: argocd
      values: |
{{- .Values.applications.argocd.values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.applications.argocd.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}