{{- if .Values.applications.certManager.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: {{ .Values.applications.certManager.chart }}
    repoURL: {{ .Values.applications.certManager.repoURL }}
    targetRevision: {{ .Values.applications.certManager.version }}
    helm:
      releaseName: cert-manager
      values: |
{{- .Values.applications.certManager.values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.applications.certManager.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
{{- end }}