{{- if .Values.applications.hypershift.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hypershift
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.applications.hypershift.repoURL }}
    targetRevision: {{ .Values.applications.hypershift.targetRevision }}
    path: {{ .Values.applications.hypershift.path }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.applications.hypershift.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
{{- end }}