{{- if .Values.applications.prometheus.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: {{ .Values.applications.prometheus.chart }}
    repoURL: {{ .Values.applications.prometheus.repoURL }}
    targetRevision: {{ .Values.applications.prometheus.version }}
    helm:
      releaseName: prometheus
      values: |
{{- .Values.applications.prometheus.values | toYaml | nindent 8 }}
  destination:
    server: {{ .Values.global.destination.server }}
    namespace: {{ .Values.applications.prometheus.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  # Ignore differences in fields managed by other controllers
  ignoreDifferences:
  # caBundle is dynamically injected by cert-manager or webhook cert controllers
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    name: prometheus-kube-prometheus-admission
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    name: prometheus-kube-prometheus-admission
    jsonPointers:
    - /webhooks/0/clientConfig/caBundle
{{- end }}