# ApplicationSet for deploying to infra-cluster labeled clusters
applicationsets:
  infra-cluster-root:
    generators:
    - clusters:
        selector:
          matchLabels:
            gcp-hcp/cluster-type: infra-cluster
        values:
          environment: "{{ .Values.cluster.environment }}"
          sector: "{{ .Values.cluster.sector }}"
          region: "{{ .Values.cluster.region }}"

    template:
      metadata:
        name: "infra-apps-{{.name}}"
        labels:
          cluster: "{{.name}}"
          cluster-type: infra-cluster
          environment: "{{ .Values.cluster.environment }}"
          sector: "{{ .Values.cluster.sector }}"
          region: "{{ .Values.cluster.region }}"
      spec:
        project: default
        source:
          repoURL: https://github.com/company/gcp-hcp-apps
          targetRevision: HEAD
          path: "rendered/infra-cluster/{{ .Values.cluster.environment }}/{{ .Values.cluster.sector }}/{{ .Values.cluster.region }}"
          helm:
            valuesObject:
              cluster:
                region: "{{ .Values.cluster.region }}"
                environment: "{{ .Values.cluster.environment }}"
                sector: "{{ .Values.cluster.sector }}"
                projectId: "{{`{{ index .metadata.annotations \"gcp-hcp/project-id\" }}`}}"
                vpcId: "{{`{{ index .metadata.annotations \"gcp-hcp/vpc-id\" }}`}}"
        destination:
          server: "{{.server}}"
          namespace: argocd
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=true
