global:
  environment: prod

applications:
  argocd:
    version: "5.45.0"  # Stable version
    values:
      controller:
        replicas: 2
      server:
        replicas: 2
        ingress:
          enabled: true
          ingressClassName: "nginx"
        service:
          type: ClusterIP
      repoServer:
        replicas: 2

  prometheus:
    version: "77.8.0"  # Stable version
    values:
      grafana:
        persistence:
          enabled: true
          size: "50Gi"
        service:
          type: ClusterIP
        replicas: 2
      prometheus:
        prometheusSpec:
          retention: "30d"  # Longer retention for prod
          replicas: 2
          resources:
            requests:
              memory: "4Gi"
              cpu: "1000m"

  certManager:
    version: "v1.17.0"  # Stable version
    values:
      replicas: 2
      webhook:
        replicas: 2