# Base configuration for prometheus
applications:
  prometheus:
    # ArgoCD source configuration
    source:
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: "77.9.1"
      chart: kube-prometheus-stack
      helm:
        valuesObject:
          grafana:
            service:
              type: ClusterIP
          # Cluster values injected by ApplicationSet
          cluster:
            region: "{{ .Values.cluster.region }}"
            projectId: "{{ .Values.cluster.projectId }}"
            vpcId: "{{ .Values.cluster.vpcId }}"

    # Deployment destination
    destination:
      namespace: monitoring

    # Application-specific configuration
    syncPolicy:
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true