apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: management-cluster-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/patjlm/gcp-hcp-apps.git
      revision: main
      files:
      - path: "management-clusters/*/application.yaml"
  template:
    metadata:
      name: '{{path[1]}}'
      namespace: argocd
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/patjlm/gcp-hcp-apps.git
        targetRevision: main
        path: '{{path[0]}}/{{path[1]}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
