# -- Deploy Argo CD Applications within this helm release
# @default -- `{}` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
applications: {}
#  guestbook:
#    namespace: argocd
#    additionalLabels: {}
#    additionalAnnotations: {}
#    finalizers:
#    - resources-finalizer.argocd.argoproj.io
#    project: guestbook
#    source:
#      repoURL: https://github.com/argoproj/argocd-example-apps.git
#      targetRevision: HEAD
#      path: guestbook
#      directory:
#        recurse: true
#    # ArgoCD v2.6 or later
#    sources:
#    - chart: elasticsearch
#      repoURL: https://helm.elastic.co
#      targetRevision: 8.5.1
#    - repoURL: https://github.com/argoproj/argocd-example-apps.git
#      path: guestbook
#      targetRevision: HEAD
#    destination:
#      server: https://kubernetes.default.svc
#      namespace: guestbook
#    syncPolicy:
#      automated:
#        prune: false
#        selfHeal: false
#      syncOptions:
#      - CreateNamespace=true
#    revisionHistoryLimit: null
#    ignoreDifferences:
#    - group: apps
#      kind: Deployment
#      jsonPointers:
#      - /spec/replicas
#    info:
#    - name: url
#      value: https://argoproj.github.io/

# -- Deploy Argo CD Projects within this helm release
# @default -- `{}` (See [values.yaml])
## Ref: https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/
