# ApplicationSet for deploying to management-cluster labeled clusters
applicationsets:
  management-cluster-root:
    generators:
    - clusters:
        selector:
          matchLabels:
            gcp-hcp/cluster-type: management-cluster
        values:
          environment: "{{ .Values.cluster.environment }}"
          sector: "{{ .Values.cluster.sector }}"
          region: "{{ .Values.cluster.region }}"

    template:
      metadata:
        name: "mgmt-apps-{{name}}"
        labels:
          cluster: "{{.name}}"
          cluster-type: management-cluster
          environment: "{{ .values.environment }}"
          sector: "{{ .values.sector }}"
          region: "{{ .values.region }}"
      spec:
        project: default
        source:
          repoURL: https://github.com/company/gcp-hcp-apps
          targetRevision: HEAD
          path: "rendered/management-cluster/{{ .values.environment }}/{{ .values.sector }}/{{ .values.region }}"
          helm:
            values: |
              clusters:
                name: {{ .name }}
                region: {{ .values.region }}
                environment: {{ .values.environment }}
                sector: {{ .values.sector }}
                project_id: '{{ index .metadata.annotations "gcp-hcp/project-id" }}'
        destination:
          server: "{{.server}}"
          namespace: argocd
        syncPolicy:
          automated:
            prune: true
            selfHeal: true
          syncOptions:
          - CreateNamespace=false
